### PR TITLE
Getting Started Guide

### PR DESCRIPTION
**Pull request by tobiastimm**
This is a draft for the getting started guide.

**Work in Progress**

### CODE REVIEW

**Comment by tobiastimm** [comment]
@irenama @rosaresa can you take a look at this? This is only a starting point, feel free to post your ideas 😄

**Comment by rosaresa** [comment]
Thank you @tobiastimm! Hopefully we have time this week to take a look at it! 🙃

**Comment by irenama** [comment]
Nice work! I really appreciate it! :) Let's give it a try next time and hand the new nodeschoolers the link to the markdown file 
by the way: 12th of september 18:00 @tobiastimm @rosaresa wanna join? :)

**Comment by tobiastimm** [comment]
@irenama yeah should work! We need to improve the guide in some parts

**Pull request merged**
